### PR TITLE
Primarily - made this plugin work for dialogue preview in the editor.

### PR DESCRIPTION
**Pull request by jon-heard**
Some code polish too
- updated order of CONFIG parameters
- Switched CONFIG parameters that represent numbers from "text" to "json"
- Also, added support for using "-" dialogue to clear dialogue state.

Note, ESlint took umbrage with the style I used to code some getters.  I'm fine with the alternate style if that's what you prefer, but the style I used is easier to read IMO, because it focuses on the repetition of the form between all of the getters.

### CODE REVIEW

**Comment by jon-heard** [comment]
Looking at this now, I realize that I could replace all `//! CODE_PLAYBACK` and `//! CODE_EDITOR` with `if` checks for window.PLAYBACK and window.EDITOR.

I think it'll read better.  I'm going to do this now.

**Comment by jon-heard** [comment]
The update from `//! CODE_` to `if` check is complete.

**Review by seleb — CHANGES_REQUESTED** [review]
tested this out, but the dialogue preview in the editor still shows the `@@X@@` text and does not show a portrait

**Comment by jon-heard** [comment]
Hmm.  This update relies on a bipsi feature added yesterday.  Might the version of bipsi that you are using not be the latest?

I'll give it another test with a fresh project.

**Comment by seleb** [comment]
> Hmm. This update relies on a bipsi feature added yesterday. Might the version of bipsi that you are using not be the latest?

double checked the version was latest but no luck, plugin still doesn't work in the editor

**Comment by jon-heard** [comment]
That's so strange.  It's working for me off of https://kool.tools/bipsi.

I'll look for options to suss out the difference.

**Comment by jon-heard** [comment]
FYI: It's not working for me in chrome, but it is in firefox.

**Comment by jon-heard** [comment]
NVM, it's working in chrome too.  I accidentally pulled the plugin from the dist folder.

**Comment by jon-heard** [comment]
Could you try checking that `window.portraitVars` is assigned while not playtesting?  That'll rule out the system not being setup in edit mode.

**Comment by seleb** [comment]
was looking into it some more and i believe there's an issue with how it's handling the IIFEs and the code segments: the editor ends up trying to run an `editorCode` block that ends with
```js

	// #endregion
	
	})();
	
	
	})();
	
````
the second IIFE closing line doesn't have a matching opening line, and the whole thing ends up not executing due to the syntax error

**Comment by jon-heard** [comment]
That code is from `dialogue portraits.js`?  The plugin doesn't use any IIFE's.  Also, there shouldn't be any editor code-type segments at this point.  I've replaced them with if checks.  There's just one code-type segment for the entire plugin: `//! CODE_ALL_TYPES` on line 81.

**Comment by jon-heard** [comment]
Is this maybe an incompatibility with the process that reads the src folder and writes to the dist folder?  If so, then I'll need a copy of plugin from the "dist" version to test with.  I'll look for how to get that.

**Comment by seleb** [comment]
> Is this maybe an incompatibility with the process that reads the src folder and writes to the dist folder? If so, then I'll need a copy of plugin from the "dist" version to test with. I'll look for how to do that.

yeah, i think it's an artifact of how the `CODE_*` blocks interact with the build process: right now the plugins are wrapped in an IIFE as part of the build process, so half of the IIFE gets chopped out by the code segments.

if you haven't run the build process locally before, all you should need are a node/npm installation and to run `npm i` followed by `npm run build`

**Comment by jon-heard** [comment]
I see that you've been fixing the editor plugins as they've been coming in.  I didn't realize that there was this incompatibility between the code-type headers and the build system.  I'll be testing my plugins with the build system going forward.

**Comment by jon-heard** [comment]
Ok.  I have a fix in place.

**Review by seleb — APPROVED** [review]

**Pull request merged**
