### PR TITLE
Add tall character plugin

### PR DESCRIPTION
**Pull request by Jummit**
Just something I missed from bitsy.

Only supports a one-tile extension (for now).

### CODE REVIEW

**Comment by seleb** [comment]
thanks for the contribution! i'll address the lint issues and do some quick cleanup, then merge this

heads up though that i actually wrote a version of multi-sprite avatar for a friend's game recently that supported more than one tile; i haven't gotten around to setting it up as a proper plugin, but if i do i might end up replacing this in the near future

**Comment by Jummit** [comment]
> heads up though that i actually wrote a version of multi-sprite avatar for a friend's game recently that supported more than one tile; i haven't gotten around to setting it up as a proper plugin, but if i do i might end up replacing this in the near future

Sounds good, I just made this to get my feet wet with bipsi. One question: It said somewhere that the properties would be added automatically when adding a plugin, but it doesn't seem to be the case. Is it just not implemented, or am I missing something?

**Comment by seleb** [comment]
> One question: It said somewhere that the properties would be added automatically when adding a plugin, but it doesn't seem to be the case. Is it just not implemented, or am I missing something?

yeah you're missing the `//!CONFIG` comments which bipsi uses to populate the default fields (i'm adding those as part of my cleanup pass)

**Comment by Jummit** [comment]
> > One question: It said somewhere that the properties would be added automatically when adding a plugin, but it doesn't seem to be the case. Is it just not implemented, or am I missing something?
> 
> yeah you're missing the `//!CONFIG` comments which bipsi uses to populate the default fields (i'm adding those as part of my cleanup pass)

Gotcha. Don't forget to replace "dowm" with "down", I overlooked that :P

**Review by seleb — APPROVED** [review]

**Pull request merged**
